//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace FrontEnd
{
    public partial class IndividualProductsPage :System.Web.UI.Page 
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }
    }
}


